[package]
name = "benerin-api"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
once_cell = "1.16.0"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]
default-features = false

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["sqlx_mysql"]
